### PR TITLE
Add CC license

### PR DESCRIPTION
**Pull request by ento**
image

### CODE REVIEW

**Comment by eeue56** [comment]
Maybe some spacing between the author and the CC license?

**Comment by ento** [comment]
Wrapped the license in a `footer`.

// I assumed we don't have a `style.css` yet when I saw there was only an html file in `./output` (just writing down my expectation for a static site generator)

**Comment by eeue56** [comment]
Ah, right. Well it's using the tumblr styles from here - https://github.com/NoRedInk/eng-blog/blob/master/style.css

**Comment by eeue56** [comment]
along with code highlighting from here -> https://github.com/NoRedInk/eng-blog/blob/master/default.css

**Comment by ento** [comment]
+added margin between author and content
+updated screenshot

**Pull request merged**
